# Change these first
owner: PascaleBeier # Your GitHub organization or username, where this repository lives
repo: buycheapsolar-uptime # The name of this repository

sites:
  - name: Homepage
    url: https://buycheapsolar.com/
  - name: Shop
    url: https://buycheapsolar.com/shop/
  - name: Checkout
    url: https://buycheapsolar.com/cart/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # baseUrl: /your-repo-name
  logoUrl: https://buycheapsolar.com/wp-content/uploads/2020/10/logo.png
  name: Buy Cheap Solar
  introTitle: "**Buy Cheap Solar** Uptime Monitor."
  introMessage: Measuring homepage, shop and checkout
  baseUrl: /buycheapsolar-uptime
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://buycheapsolar.com/
    - title: Shop
      href: https://buycheapsolar.com/shop/
    - title: Cart
      href: https://buycheapsolar.com/cart/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
